//
// Created by haridev on 10/5/23.
//

#ifndef DFTRACER_CONSTANTS_H
#define DFTRACER_CONSTANTS_H

#include <stddef.h>

#define DFTRACER_CONFIGURATION "DFTRACER_CONFIGURATION"
#define DFTRACER_ENABLE "DFTRACER_ENABLE"
#define DFTRACER_GOTCHA_PRIORITY "DFTRACER_GOTCHA_PRIORITY"
#define DFTRACER_LOG_LEVEL "DFTRACER_LOG_LEVEL"
#define DFTRACER_TIME_METRIC "DFTRACER_TIME_METRIC"
#define DFTRACER_LOG_FILE "DFTRACER_LOG_FILE"
#define DFTRACER_INIT "DFTRACER_INIT"
#define DFTRACER_INIT_COUNT "DFTRACER_INIT_COUNT"
#define DFTRACER_DATA_DIR "DFTRACER_DATA_DIR"
#define DFTRACER_DATA_DIR_DELIMITER ':'
#define DFTRACER_SET_CORE_AFFINITY "DFTRACER_SET_CORE_AFFINITY"
#define DFTRACER_ERROR "DFTRACER_ERROR"
#define DFTRACER_INC_METADATA "DFTRACER_INC_METADATA"
#define DFTRACER_DISABLE_POSIX "DFTRACER_DISABLE_POSIX"
#define DFTRACER_DISABLE_STDIO "DFTRACER_DISABLE_STDIO"
#define DFTRACER_DISABLE_IO "DFTRACER_DISABLE_IO"
#define DFTRACER_TRACE_COMPRESSION "DFTRACER_TRACE_COMPRESSION"
#define DFTRACER_DISABLE_TIDS "DFTRACER_DISABLE_TIDS"
#define DFTRACER_ENABLE_AGGREGATION "DFTRACER_ENABLE_AGGREGATION"
#define DFTRACER_AGGREGATION_TYPE "DFTRACER_AGGREGATION_TYPE"
#define DFTRACER_AGGREGATION_FILE "DFTRACER_AGGREGATION_FILE"
#define DFTRACER_BIND_SIGNALS "DFTRACER_BIND_SIGNALS"
#define DFTRACER_WRITE_BUFFER_SIZE "DFTRACER_WRITE_BUFFER_SIZE"
#define DFTRACER_TRACE_INTERVAL_MS "DFTRACER_TRACE_INTERVAL_MS"
#define DFTRACER_LIBUV_THREADS "DFTRACER_LIBUV_THREADS"
#define DFTRACER_ENABLE_PAPI_TRACING "DFTRACER_ENABLE_PAPI_TRACING"
#define DFTRACER_PAPI_EVENTS "DFTRACER_PAPI_EVENTS"
#define DFTRACER_PAPI_MULTIPLEX "DFTRACER_PAPI_MULTIPLEX"
#define DFTRACER_PAPI_SAMPLE_INTERVAL_MS "DFTRACER_PAPI_SAMPLE_INTERVAL_MS"
#define DFTRACER_DISABLE_VARIORUM_POWER "DFTRACER_DISABLE_VARIORUM_POWER"
#define DFTRACER_ALL_FILES "all"
#define DFTRACER_DEFAULT_AGGREGATION_RULE "dur < 100"
#define DFTRACER_AGGREGATOR_COUNT "dft_cnt"

static const int EVENT_TYPE_SIZE = 128;
static const unsigned int DFT_PATH_MAX = 1024 * 4;
static const char SEPARATOR = ';';
static const int HASH_OUTPUT = 16;
#define NO_HASH_DEFAULT 0
// Size of the traced-descriptor table when no limit is known, and its cap. The
// cap is 32 MB of address space for 8-byte hashes.
static const size_t DFT_DEFAULT_MAX_FD = 1024;
static const size_t DFT_MAX_TRACKED_FD = 4194304;

#endif  // DFTRACER_CONSTANTS_H
