///
/// This file is generated by tools/generate_interfaces_from_brahma.py
/// Generated on: 2026-02-23 13:45:52
///
/// This is a dftracer stub file. Regenerate and customize as needed.
///

#ifndef DFTRACER_MPIIO_H
#define DFTRACER_MPIIO_H

#include <brahma/brahma.h>
#include <dftracer/core/common/constants.h>
#include <dftracer/core/common/logging.h>
#include <dftracer/core/common/typedef.h>

#ifdef BRAHMA_ENABLE_MPI
#include <dftracer/core/df_logger.h>
#include <mpi.h>

namespace brahma {

class MPIIODFTracer : public MPIIO {
 private:
  static std::shared_ptr<MPIIODFTracer> instance;
  static bool stop_trace;
  std::shared_ptr<DFTLogger> logger;

 public:
  MPIIODFTracer() : MPIIO() { logger = DFT_LOGGER_INIT(); }

  virtual ~MPIIODFTracer() {}

  static std::shared_ptr<MPIIODFTracer> get_instance() {
    if (!stop_trace && instance == nullptr) {
      instance = std::make_shared<MPIIODFTracer>();
      MPIIO::set_instance(instance);
    }
    return instance;
  }

  void finalize() { stop_trace = true; }

#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_call_errhandler(MPI_File fh, int errorcode) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_close(MPI_File* fh) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_create_errhandler(MPI_File_errhandler_function* function,
                                 MPI_Errhandler* errhandler) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_delete(const char* filename, MPI_Info info) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_amode(MPI_File fh, int* amode) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_atomicity(MPI_File fh, int* flag) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_byte_offset(MPI_File fh, MPI_Offset offset,
                               MPI_Offset* disp) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_errhandler(MPI_File file,
                              MPI_Errhandler* errhandler) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_group(MPI_File fh, MPI_Group* group) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_info(MPI_File fh, MPI_Info* info_used) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_position(MPI_File fh, MPI_Offset* offset) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_position_shared(MPI_File fh, MPI_Offset* offset) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_size(MPI_File fh, MPI_Offset* size) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_type_extent(MPI_File fh, MPI_Datatype datatype,
                               MPI_Aint* extent) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_get_type_extent_c(MPI_File fh, MPI_Datatype datatype,
                                 MPI_Count* extent) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_get_view(MPI_File fh, MPI_Offset* disp, MPI_Datatype* etype,
                        MPI_Datatype* filetype, char* datarep) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iread(MPI_File fh, void* buf, int count, MPI_Datatype datatype,
                     MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iread_all(MPI_File fh, void* buf, int count,
                         MPI_Datatype datatype, MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iread_all_c(MPI_File fh, void* buf, MPI_Count count,
                           MPI_Datatype datatype,
                           MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iread_at(MPI_File fh, MPI_Offset offset, void* buf, int count,
                        MPI_Datatype datatype, MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iread_at_all(MPI_File fh, MPI_Offset offset, void* buf,
                            int count, MPI_Datatype datatype,
                            MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iread_at_all_c(MPI_File fh, MPI_Offset offset, void* buf,
                              MPI_Count count, MPI_Datatype datatype,
                              MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iread_at_c(MPI_File fh, MPI_Offset offset, void* buf,
                          MPI_Count count, MPI_Datatype datatype,
                          MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iread_c(MPI_File fh, void* buf, MPI_Count count,
                       MPI_Datatype datatype, MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iread_shared(MPI_File fh, void* buf, int count,
                            MPI_Datatype datatype,
                            MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iread_shared_c(MPI_File fh, void* buf, MPI_Count count,
                              MPI_Datatype datatype,
                              MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iwrite(MPI_File fh, const void* buf, int count,
                      MPI_Datatype datatype, MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iwrite_all(MPI_File fh, const void* buf, int count,
                          MPI_Datatype datatype, MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iwrite_all_c(MPI_File fh, const void* buf, MPI_Count count,
                            MPI_Datatype datatype,
                            MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iwrite_at(MPI_File fh, MPI_Offset offset, const void* buf,
                         int count, MPI_Datatype datatype,
                         MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iwrite_at_all(MPI_File fh, MPI_Offset offset, const void* buf,
                             int count, MPI_Datatype datatype,
                             MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iwrite_at_all_c(MPI_File fh, MPI_Offset offset, const void* buf,
                               MPI_Count count, MPI_Datatype datatype,
                               MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iwrite_at_c(MPI_File fh, MPI_Offset offset, const void* buf,
                           MPI_Count count, MPI_Datatype datatype,
                           MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iwrite_c(MPI_File fh, const void* buf, MPI_Count count,
                        MPI_Datatype datatype, MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_iwrite_shared(MPI_File fh, const void* buf, int count,
                             MPI_Datatype datatype,
                             MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_iwrite_shared_c(MPI_File fh, const void* buf, MPI_Count count,
                               MPI_Datatype datatype,
                               MPI_Request* request) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_open(MPI_Comm comm, const char* filename, int amode,
                    MPI_Info info, MPI_File* fh) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_preallocate(MPI_File fh, MPI_Offset size) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read(MPI_File fh, void* buf, int count, MPI_Datatype datatype,
                    MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_all(MPI_File fh, void* buf, int count,
                        MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_all_begin(MPI_File fh, void* buf, int count,
                              MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_all_begin_c(MPI_File fh, void* buf, MPI_Count count,
                                MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_all_c(MPI_File fh, void* buf, MPI_Count count,
                          MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_all_end(MPI_File fh, void* buf,
                            MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_at(MPI_File fh, MPI_Offset offset, void* buf, int count,
                       MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_at_all(MPI_File fh, MPI_Offset offset, void* buf, int count,
                           MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_at_all_begin(MPI_File fh, MPI_Offset offset, void* buf,
                                 int count, MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_at_all_begin_c(MPI_File fh, MPI_Offset offset, void* buf,
                                   MPI_Count count,
                                   MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_at_all_c(MPI_File fh, MPI_Offset offset, void* buf,
                             MPI_Count count, MPI_Datatype datatype,
                             MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_at_all_end(MPI_File fh, void* buf,
                               MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_at_c(MPI_File fh, MPI_Offset offset, void* buf,
                         MPI_Count count, MPI_Datatype datatype,
                         MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_c(MPI_File fh, void* buf, MPI_Count count,
                      MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_ordered(MPI_File fh, void* buf, int count,
                            MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_ordered_begin(MPI_File fh, void* buf, int count,
                                  MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_ordered_begin_c(MPI_File fh, void* buf, MPI_Count count,
                                    MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_ordered_c(MPI_File fh, void* buf, MPI_Count count,
                              MPI_Datatype datatype,
                              MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_ordered_end(MPI_File fh, void* buf,
                                MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_read_shared(MPI_File fh, void* buf, int count,
                           MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_read_shared_c(MPI_File fh, void* buf, MPI_Count count,
                             MPI_Datatype datatype,
                             MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_seek(MPI_File fh, MPI_Offset offset, int whence) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_seek_shared(MPI_File fh, MPI_Offset offset, int whence) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_set_atomicity(MPI_File fh, int flag) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_set_errhandler(MPI_File file,
                              MPI_Errhandler errhandler) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_set_info(MPI_File fh, MPI_Info info) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_set_size(MPI_File fh, MPI_Offset size) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_set_view(MPI_File fh, MPI_Offset disp, MPI_Datatype etype,
                        MPI_Datatype filetype, const char* datarep,
                        MPI_Info info) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_sync(MPI_File fh) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write(MPI_File fh, const void* buf, int count,
                     MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_all(MPI_File fh, const void* buf, int count,
                         MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_all_begin(MPI_File fh, const void* buf, int count,
                               MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_all_begin_c(MPI_File fh, const void* buf, MPI_Count count,
                                 MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_all_c(MPI_File fh, const void* buf, MPI_Count count,
                           MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_all_end(MPI_File fh, const void* buf,
                             MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_at(MPI_File fh, MPI_Offset offset, const void* buf,
                        int count, MPI_Datatype datatype,
                        MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_at_all(MPI_File fh, MPI_Offset offset, const void* buf,
                            int count, MPI_Datatype datatype,
                            MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_at_all_begin(MPI_File fh, MPI_Offset offset,
                                  const void* buf, int count,
                                  MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_at_all_begin_c(MPI_File fh, MPI_Offset offset,
                                    const void* buf, MPI_Count count,
                                    MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_at_all_c(MPI_File fh, MPI_Offset offset, const void* buf,
                              MPI_Count count, MPI_Datatype datatype,
                              MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_at_all_end(MPI_File fh, const void* buf,
                                MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_at_c(MPI_File fh, MPI_Offset offset, const void* buf,
                          MPI_Count count, MPI_Datatype datatype,
                          MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_c(MPI_File fh, const void* buf, MPI_Count count,
                       MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_ordered(MPI_File fh, const void* buf, int count,
                             MPI_Datatype datatype,
                             MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_ordered_begin(MPI_File fh, const void* buf, int count,
                                   MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_ordered_begin_c(MPI_File fh, const void* buf,
                                     MPI_Count count,
                                     MPI_Datatype datatype) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_ordered_c(MPI_File fh, const void* buf, MPI_Count count,
                               MPI_Datatype datatype,
                               MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_ordered_end(MPI_File fh, const void* buf,
                                 MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) && ((BRAHMA_MPI_VERSION >= 800108 && BRAHMA_MPI_VERSION < 800200) || (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100))) || (defined(BRAHMA_MPI_IMPL_MPICH) && ((BRAHMA_MPI_VERSION >= 300403 && BRAHMA_MPI_VERSION < 300500) || (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300))) || (defined(BRAHMA_MPI_IMPL_MVAPICH) && (BRAHMA_MPI_VERSION >= 200300 && BRAHMA_MPI_VERSION < 200400)) || (defined(BRAHMA_MPI_IMPL_OPENMPI) && ((BRAHMA_MPI_VERSION >= 400106 && BRAHMA_MPI_VERSION < 400200) || (BRAHMA_MPI_VERSION >= 500006 && BRAHMA_MPI_VERSION < 500100))))
  int MPI_File_write_shared(MPI_File fh, const void* buf, int count,
                            MPI_Datatype datatype, MPI_Status* status) override;
#endif
#if ((defined(BRAHMA_MPI_IMPL_CRAYMPICH) &&                             \
      (BRAHMA_MPI_VERSION >= 900001 && BRAHMA_MPI_VERSION < 900100)) || \
     (defined(BRAHMA_MPI_IMPL_MPICH) &&                                 \
      (BRAHMA_MPI_VERSION >= 400203 && BRAHMA_MPI_VERSION < 400300)))
  int MPI_File_write_shared_c(MPI_File fh, const void* buf, MPI_Count count,
                              MPI_Datatype datatype,
                              MPI_Status* status) override;
#endif
};
}  // namespace brahma

#endif  // BRAHMA_ENABLE_MPI
#endif  // DFTRACER_MPIIO_H
